### ISSUE TITLE
polymer serve got errors

### ISSUE THREAD

**Issue by sidealice** [Polymer/shop#37]
usr/lib/node_modules/polymer-cli/bin/polymer.js:19
  let lib = path ? require(path) : require('..');
  ^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

**Comment by frankiefu** [comment]
Can you file the issue in [polymer-cli](https://github.com/Polymer/polymer-cli)?
