### ISSUE TITLE
The Shop App fails to build

### ISSUE THREAD

**Issue by innomon** [Polymer/shop#44]
I am using nodejs  **v4.4.5**
The polymer cli is able to serve the app but fails to build, as it is unable to find the module `sw-toolbox/sw-toolbox.js`
I even installed the [`GoogleChrome/sw-toolbox`](https://github.com/GoogleChrome/sw-toolbox) but still did not work.

Here is the build dump:

`ab$ polymer build
info:    Building application...
info:    Generating build/unbundled...
info:    Generating build/bundled...
warn:    Unable to uglify file /home/ashish/GitLabs/Megh/shop/bower_components/web-component-tester/data/index.html_script_0.js
warn:    Unable to uglify file /home/ashish/GitLabs/Megh/shop/bower_components/web-component-tester/data/index.html_script_2.js
info:    Generating service workers...
error:   Promise rejection: Error: Cannot find module 'sw-toolbox/sw-toolbox.js'
error:   Error: Cannot find module 'sw-toolbox/sw-toolbox.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.require.resolve (internal/module.js:16:19)
    at /home/ashish/.nvm/versions/node/v4.4.5/lib/node_modules/polymer-cli/node_modules/sw-precache/lib/sw-precache.js:184:37
    at new Promise (/home/ashish/.nvm/versions/node/v4.4.5/lib/node_modules/polymer-cli/node_modules/hydrolysis/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:193:7)
    at generate (/home/ashish/.nvm/versions/node/v4.4.5/lib/node_modules/polymer-cli/node_modules/sw-precache/lib/sw-precache.js:78:10)
    at /home/ashish/.nvm/versions/node/v4.4.5/lib/node_modules/polymer-cli/node_modules/sw-precache/lib/sw-precache.js:295:5
    at new Promise (/home/ashish/.nvm/versions/node/v4.4.5/lib/node_modules/polymer-cli/node_modules/hydrolysis/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:193:7)
    at Object.write (/home/ashish/.nvm/versions/node/v4.4.5/lib/node_modules/polymer-cli/node_modules/sw-precache/lib/sw-precache.js:275:10)
    at writeSWPrecache (/home/ashish/.nvm/versions/node/v4.4.5/lib/node_modules/polymer-cli/lib/build/sw-precache.js:20:23)
    at Object.generateServiceWorker (/home/ashish/.nvm/versions/node/v4.4.5/lib/node_modules/polymer-cli/lib/build/sw-precache.js:47:12)
error:   Promise rejection: Error: Cannot find module 'sw-toolbox/sw-toolbox.js'
error:   Error: Cannot find module 'sw-toolbox/sw-toolbox.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.require.resolve (internal/module.js:16:19)
    at /home/ashish/.nvm/versions/node/v4.4.5/lib/node_modules/polymer-cli/node_modules/sw-precache/lib/sw-precache.js:184:37
    at new Promise (/home/ashish/.nvm/versions/node/v4.4.5/lib/node_modules/polymer-cli/node_modules/hydrolysis/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:193:7)
    at generate (/home/ashish/.nvm/versions/node/v4.4.5/lib/node_modules/polymer-cli/node_modules/sw-precache/lib/sw-precache.js:78:10)
    at /home/ashish/.nvm/versions/node/v4.4.5/lib/node_modules/polymer-cli/node_modules/sw-precache/lib/sw-precache.js:295:5
    at new Promise (/home/ashish/.nvm/versions/node/v4.4.5/lib/node_modules/polymer-cli/node_modules/hydrolysis/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:193:7)
    at Object.write (/home/ashish/.nvm/versions/node/v4.4.5/lib/node_modules/polymer-cli/node_modules/sw-precache/lib/sw-precache.js:275:10)
    at writeSWPrecache (/home/ashish/.nvm/versions/node/v4.4.5/lib/node_modules/polymer-cli/lib/build/sw-precache.js:20:23)
    at Object.generateServiceWorker (/home/ashish/.nvm/versions/node/v4.4.5/lib/node_modules/polymer-cli/lib/build/sw-precache.js:47:12)
ab$ 
`

**Comment by frankiefu** [comment]
This is a polymer-cli issue as already reported here: https://github.com/Polymer/polymer-cli/issues/250
